wget -P assets/images/resources https://pixydrops.com/ogenix/main-html/assets/images/resources/logo-1.png
wget -P assets/images/home-showcase https://pixydrops.com/ogenix/main-html/assets/images/home-showcase/home-showcase-1-1.jpg
wget -P assets/images/home-showcase https://pixydrops.com/ogenix/main-html/assets/images/home-showcase/home-showcase-1-2.jpg
wget -P assets/images/home-showcase https://pixydrops.com/ogenix/main-html/assets/images/home-showcase/home-showcase-1-3.jpg
wget -P assets/images/home-showcase https://pixydrops.com/ogenix/main-html/assets/images/home-showcase/home-showcase-1-4.jpg
wget -P assets/images/shop https://pixydrops.com/ogenix/main-html/assets/images/shop/paypal-1.jpg
wget -P assets/images/shapes https://pixydrops.com/ogenix/main-html/assets/images/shapes/subscribe-one-shape-1.png
wget -P assets/images/shapes https://pixydrops.com/ogenix/main-html/assets/images/shapes/subscribe-one-shape-2.png
wget -P assets/images/shapes https://pixydrops.com/ogenix/main-html/assets/images/shapes/subscribe-one-shape-4.png
wget -P assets/images/shapes https://pixydrops.com/ogenix/main-html/assets/images/shapes/subscribe-one-shape-5.png
wget -P assets/images/shapes https://pixydrops.com/ogenix/main-html/assets/images/shapes/subscribe-one-shape-3.png
wget -P assets/images/shapes https://pixydrops.com/ogenix/main-html/assets/images/shapes/subscribe-one-shape-6.png
wget -P assets/images/resources https://pixydrops.com/ogenix/main-html/assets/images/resources/footer-logo.png
wget -P assets/images/resources https://pixydrops.com/ogenix/main-html/assets/images/resources/footer-widget-gallery-img-1.jpg
wget -P assets/images/resources https://pixydrops.com/ogenix/main-html/assets/images/resources/footer-widget-gallery-img-2.jpg
wget -P assets/images/resources https://pixydrops.com/ogenix/main-html/assets/images/resources/footer-widget-gallery-img-3.jpg
wget -P assets/images/resources https://pixydrops.com/ogenix/main-html/assets/images/resources/footer-widget-gallery-img-4.jpg
wget -P assets/images/resources https://pixydrops.com/ogenix/main-html/assets/images/resources/footer-widget-gallery-img-5.jpg
wget -P assets/images/resources https://pixydrops.com/ogenix/main-html/assets/images/resources/footer-widget-gallery-img-6.jpg
wget -P assets/images/resources https://pixydrops.com/ogenix/main-html/assets/images/resources/logo-1.png
wget -P assets/vendors/jquery https://pixydrops.com/ogenix/main-html/assets/vendors/jquery/jquery-3.6.0.min.js
wget -P assets/vendors/bootstrap/js https://pixydrops.com/ogenix/main-html/assets/vendors/bootstrap/js/bootstrap.bundle.min.js
wget -P assets/vendors/jarallax https://pixydrops.com/ogenix/main-html/assets/vendors/jarallax/jarallax.min.js
wget -P assets/vendors/jquery-ajaxchimp https://pixydrops.com/ogenix/main-html/assets/vendors/jquery-ajaxchimp/jquery.ajaxchimp.min.js
wget -P assets/vendors/jquery-appear https://pixydrops.com/ogenix/main-html/assets/vendors/jquery-appear/jquery.appear.min.js
wget -P assets/vendors/jquery-circle-progress https://pixydrops.com/ogenix/main-html/assets/vendors/jquery-circle-progress/jquery.circle-progress.min.js
wget -P assets/vendors/jquery-magnific-popup https://pixydrops.com/ogenix/main-html/assets/vendors/jquery-magnific-popup/jquery.magnific-popup.min.js
wget -P assets/vendors/jquery-validate https://pixydrops.com/ogenix/main-html/assets/vendors/jquery-validate/jquery.validate.min.js
wget -P assets/vendors/nouislider https://pixydrops.com/ogenix/main-html/assets/vendors/nouislider/nouislider.min.js
wget -P assets/vendors/odometer https://pixydrops.com/ogenix/main-html/assets/vendors/odometer/odometer.min.js
wget -P assets/vendors/swiper https://pixydrops.com/ogenix/main-html/assets/vendors/swiper/swiper.min.js
wget -P assets/vendors/tiny-slider https://pixydrops.com/ogenix/main-html/assets/vendors/tiny-slider/tiny-slider.min.js
wget -P assets/vendors/wnumb https://pixydrops.com/ogenix/main-html/assets/vendors/wnumb/wNumb.min.js
wget -P assets/vendors/wow https://pixydrops.com/ogenix/main-html/assets/vendors/wow/wow.js
wget -P assets/vendors/isotope https://pixydrops.com/ogenix/main-html/assets/vendors/isotope/isotope.js
wget -P assets/vendors/countdown https://pixydrops.com/ogenix/main-html/assets/vendors/countdown/jquery.countdown.min.js
wget -P assets/vendors/owl-carousel https://pixydrops.com/ogenix/main-html/assets/vendors/owl-carousel/owl.carousel.min.js
wget -P assets/vendors/bxslider https://pixydrops.com/ogenix/main-html/assets/vendors/bxslider/jquery.bxslider.min.js
wget -P assets/vendors/bootstrap-select/js https://pixydrops.com/ogenix/main-html/assets/vendors/bootstrap-select/js/bootstrap-select.min.js
wget -P assets/vendors/vegas https://pixydrops.com/ogenix/main-html/assets/vendors/vegas/vegas.min.js
wget -P assets/vendors/jquery-ui https://pixydrops.com/ogenix/main-html/assets/vendors/jquery-ui/jquery-ui.js
wget -P assets/vendors/timepicker https://pixydrops.com/ogenix/main-html/assets/vendors/timepicker/timePicker.js
wget -P assets/vendors/circleType https://pixydrops.com/ogenix/main-html/assets/vendors/circleType/jquery.circleType.js
wget -P assets/vendors/circleType https://pixydrops.com/ogenix/main-html/assets/vendors/circleType/jquery.lettering.min.js
wget -P assets/vendors/nice-select https://pixydrops.com/ogenix/main-html/assets/vendors/nice-select/jquery.nice-select.min.js
wget -P assets/js https://pixydrops.com/ogenix/main-html/assets/js/ogenix.js
